const codes = {
    page1: [
        { code: "10-0", description: "Use caution" },
        { code: "10-1", description: "Frequency change" },
        { code: "10-2", description: "Negative" },
        { code: "10-3", description: "Stop transmitting" },
        { code: "10-4", description: "Acknowledge (Ok)" },
        { code: "10-5", description: "Meal break" },
        { code: "10-6", description: "Busy" },
        { code: "10-7", description: "Out of service" },
        { code: "10-8", description: "In service" },
        { code: "10-9", description: "Repeat transmission" },
        { code: "10-10", description: "Fight in progress" },
        { code: "10-11", description: "Traffic stop" },
        { code: "10-12", description: "Active ride along" },
        { code: "10-13", description: "Shots fired" },
        { code: "10-14", description: "Suspect in custody" },
        { code: "10-15", description: "Transporting to station" },
        { code: "10-16", description: "Stolen vehicle" },
        { code: "10-17", description: "Suspicious person" },
        { code: "10-20", description: "Location" },
        { code: "10-22", description: "Disregard" },
        { code: "10-23", description: "Arrived on scene" },
        { code: "10-25", description: "Domestic dispute / disturbance" },
        { code: "10-26", description: "ETA (Estimated Time of Arrival​)" },
        { code: "10-27", description: "License check for valid" },
        { code: "10-28", description: "Plate check for valid" }
    ],
    page2: [
        { code: "10-29", description: "Warrant check" },
        { code: "10-30", description: "Wanted person" },
        { code: "10-31", description: "Not wanted / no warrants" },
        { code: "10-32", description: "Request backup (code 1-2-3)" },
        { code: "10-35", description: "Wrap the scene up" },
        { code: "10-41", description: "Beginning of shift" },
        { code: "10-42", description: "Ending of shift" },
        { code: "10-49", description: "Homicide" },
        { code: "10-50", description: "Vehicle accident" },
        { code: "10-51", description: "Request tow" },
        { code: "10-52", description: "Request EMS" }
    ],
    page3: [
        { code: "10-53", description: "Request Fire Dept" },
        { code: "10-55", description: "Intoxicated driver" },
        { code: "10-56", description: "Intoxicated Pedestrian" },
        { code: "10-60", description: "Person armed with a gun" },
        { code: "10-61", description: "Person armed with a knife" },
        { code: "10-62", description: "Kidnapping" },
        { code: "10-65", description: "Escorting prisoner" },
        { code: "10-66", description: "Reckless driver" },
        { code: "10-67", description: "Fire" },
        { code: "10-68", description: "Armed robbery" },
        { code: "10-70", description: "Foot pursuit" },
        { code: "10-71", description: "Request supervisor" },
        { code: "10-80", description: "Vehicle pursuit" },
        { code: "10-97", description: "En route" }
    ]
};